- name: Install initial packages
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - python3-debian

- shell: lsb_release -sc
  register: os_codename

- name: Add repository using the deb822 format
  ansible.builtin.deb822_repository:
    name: "Docker"
    types:
      - deb
    architectures:
      - arm64
    uris:
      - https://download.docker.com/linux/debian
    suites:
      - "{{ os_codename.stdout }}"
    components:
      - stable
    signed_by: https://download.docker.com/linux/debian/gpg
    enabled: true
  become: true

- name: Install docker packages
  become: true
  apt:
    update_cache: true
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Reboot the machine to make the docker.service start # see: https://bbs.archlinux.org/viewtopic.php?id=267694
  become: true
  reboot:

- name: Enable docker.service
  become: true
  service:
    name: docker
    state: restarted
    enabled: yes
    
- name: Create "docker" group
  become: true
  group:
    name: docker
    state: present

- name: Add user to "docker" group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes