- name: Create base service directory
  file:
    path: "{{ docker_base_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  become: true

- name: Create persistent data directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ docker_base_dir }}/homeassistant"
    - "{{ docker_base_dir }}/pihole/etc-pihole"
    - "{{ docker_base_dir }}/pihole/etc-dnsmasq.d"
    - "{{ docker_base_dir }}/jellyfin/config"
    - "{{ docker_base_dir }}/jellyfin/cache"
    - "{{ docker_base_dir }}/jellyfin/media"
    - "{{ docker_base_dir }}/traefik"

- name: Copy docker-compose file
  copy:
    src: files/docker-compose.yml
    dest: "{{ docker_base_dir }}/docker-compose.yml"
    mode: "0644"

- name: Copy .env
  copy:
    src: files/.env
    dest: "{{ docker_base_dir }}/.env"
    mode: "0600"

- name: Copy Traefik config
  copy:
    src: files/traefik.yml
    dest: "{{ docker_base_dir }}/traefik/traefik.yml"
    mode: "0644"

- name: Create acme.json
  file:
    path: "{{ docker_base_dir }}/traefik/acme.json"
    state: touch
    mode: "0600"

- name: Copy Home Assistant config
  copy:
    src: files/homeassistant.yaml
    dest: "{{ docker_base_dir }}/homeassistant/configuration.yaml"
    mode: "0644"