api:
  dashboard: true

ping:
  entrypoint: ping

log:
  level: debug

entryPoints:
  ping:
    address: ":8082"
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    asDefault: true
    http:
      tls:
        domains:
          main: cloud-vii.net
          sans:
            - '*.cloud-vii.net'
        certresolver: letsencrypt

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: ryanrod@vt.edu
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 60
        disablePropagationCheck: true
        resolvers:
          - cheryl.ns.cloudflare.com
          - luke.ns.cloudflare.com
global:
  sendanonymoususage: false